.ifndef DOTCOPYRIGHT_INC
DOTCOPYRIGHT_INC = 1
;==========================================================================================================
; compiltetime:   .dword  .time ; in POSIX Epoch time
copyr1: .byte $00,$00,$00,$00, $28,$63,$29,$20, $4B,$41,$52,$4C, $20,$4B,$55,$45
copyr2: .byte $48,$4E,$2C,$20, $44,$4C,$36,$4D, $46,$4A,$2C,$20, $32,$30,$32,$34,$00,$04
;==========================================================================================================
.endif
;==========================================================================================================
; MIT License
;
; Copyright (c) 2024 Karl Kühn, aka edrive
;
; Permission is hereby granted, free of charge, to any person obtaining a copy
; of this software and associated documentation files (the "Software"), to deal
; in the Software without restriction, including without limitation the rights
; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
; copies of the Software, and to permit persons to whom the Software is
; furnished to do so, subject to the following conditions:
;
; The above copyright notice and this permission notice shall be included in all
; copies or substantial portions of the Software.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
; SOFTWARE.
;==========================================================================================================
